export const KZ_CITIES = [
  "Алматы",
  "Астана",
  "Шымкент",
  "Ақтөбе",
  "Қарағанды",
  "Тараз",
  "Павлодар",
  "Өскемен",
  "Семей",
  "Атырау",
  "Қостанай",
  "Қызылорда",
  "Орал",
  "Петропавл",
  "Ақтау",
  "Түркістан",
];

export const EVENT_TYPES = [
  "Той",
  "Үйлену той",
  "Қыз ұзату",
  "Құдалық",
  "Сырға салу",
  "Беташар",
  "Мерейтой",
  "Тұсаукесер",
  "Сүндет той",
  "Корпоратив",
  "Туған күн",
];

export const CATEGORIES = [
  { id: "halls", name: "Залы", icon: "building", active: true, order: 1 },
  { id: "restaurants", name: "Рестораны", icon: "utensils", active: true, order: 2 },
  { id: "tamada", name: "Тамада", icon: "mic", active: true, order: 3 },
  { id: "photo", name: "Фото", icon: "camera", active: true, order: 4 },
  { id: "video", name: "Видео", icon: "video", active: true, order: 5 },
  { id: "mobile", name: "Мобилограф", icon: "phone", active: true, order: 6 },
  { id: "decor", name: "Декор", icon: "sparkles", active: true, order: 7 },
  { id: "music", name: "Музыка", icon: "music", active: true, order: 8 },
  { id: "singers", name: "Әншілер", icon: "music", active: true, order: 9 },
  { id: "show", name: "Шоу программа", icon: "star", active: true, order: 10 },
  { id: "cortege", name: "Кортеж", icon: "car", active: true, order: 11 },
  { id: "dress", name: "Көйлек", icon: "heart", active: true, order: 12 },
  { id: "makeup", name: "Макияж", icon: "user", active: true, order: 13 },
  { id: "cake", name: "Торт", icon: "cake", active: true, order: 14 },
  { id: "catering", name: "Catering", icon: "utensils", active: true, order: 15 },
  { id: "organizer", name: "Event organizer", icon: "clipboard", active: true, order: 16 },
];

export const VENDOR_SEED = [
  {
    id: "palazzo",
    ownerId: "vendor_seed_palazzo",
    businessName: "Palazzo Di Astana",
    title: "Palazzo Di Astana",
    category: "Залы",
    city: "Астана",
    district: "Есіл",
    description:
      "Классический банкетный зал с высокой сценой, LED-экраном и отдельной VIP-зоной для больших мероприятий.",
    priceFrom: 15000,
    capacity: 500,
    rating: 4.9,
    reviewsCount: 342,
    verified: true,
    featured: true,
    status: "approved",
    phone: "+77001234567",
    whatsapp: "77001234567",
    instagram: "palazzo.astana",
    image: "https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&q=80&w=1200",
    features: ["Парковка", "Halal menu", "VIP room", "Stage", "LED screen", "Photo zone"],
    availableDates: ["2026-06-12", "2026-07-20", "2026-09-14"],
  },
  {
    id: "bakshasaray",
    ownerId: "vendor_seed_bakshasaray",
    businessName: "Бақшасарай",
    title: "Бақшасарай",
    category: "Рестораны",
    city: "Алматы",
    district: "Бостандық",
    description:
      "Кең залдары бар премиум ресторан: қазақы дастархан, заманауи сервис және бірнеше форматтағы банкет залдары.",
    priceFrom: 18000,
    capacity: 700,
    rating: 5,
    reviewsCount: 820,
    verified: true,
    featured: true,
    status: "approved",
    phone: "+77007654321",
    whatsapp: "77007654321",
    instagram: "bakshasaray.almaty",
    image: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?auto=format&fit=crop&q=80&w=1200",
    features: ["Halal menu", "Terrace", "Stage", "Parking", "Children room"],
    availableDates: ["2026-06-02", "2026-08-11", "2026-10-05"],
  },
  {
    id: "aura",
    ownerId: "vendor_seed_aura",
    businessName: "Aura Palace",
    title: "Aura Palace",
    category: "Залы",
    city: "Шымкент",
    district: "Әл-Фараби",
    description:
      "Жылы атмосферасы бар заманауи зал. Оңтүстік стиліндегі ас мәзірі, жарық шоу және фотозона дайын.",
    priceFrom: 10000,
    capacity: 400,
    rating: 4.8,
    reviewsCount: 156,
    verified: true,
    featured: false,
    status: "approved",
    phone: "+77001112233",
    whatsapp: "77001112233",
    instagram: "aurapalace.kz",
    image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&q=80&w=1200",
    features: ["Photo zone", "Stage", "Parking", "LED screen"],
    availableDates: ["2026-06-18", "2026-09-01", "2026-11-09"],
  },
  {
    id: "aisha-photo",
    ownerId: "vendor_seed_aisha",
    businessName: "Aisha Wedding Photo",
    title: "Aisha Wedding Photo",
    category: "Фото",
    city: "Алматы",
    district: "Медеу",
    description:
      "Той, қыз ұзату және құдалыққа арналған editorial-style фото. Түсірілімнен кейін 7 күнде preview беріледі.",
    priceFrom: 240000,
    capacity: null,
    rating: 4.9,
    reviewsCount: 91,
    verified: true,
    featured: false,
    status: "approved",
    phone: "+77005554433",
    whatsapp: "77005554433",
    instagram: "aisha.photo",
    image: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&q=80&w=1200",
    features: ["Same day preview", "Love story", "Album", "Drone optional"],
    availableDates: ["2026-06-04", "2026-07-19", "2026-09-21"],
  },
  {
    id: "arman-tamada",
    ownerId: "vendor_seed_arman",
    businessName: "Arman Show",
    title: "Arman Show",
    category: "Тамада",
    city: "Астана",
    district: "Сарыарқа",
    description:
      "Қазақша және орысша жүргізетін premium тамада. Сценарий, ойындар және live coordination кіреді.",
    priceFrom: 450000,
    capacity: null,
    rating: 4.7,
    reviewsCount: 64,
    verified: true,
    featured: false,
    status: "approved",
    phone: "+77002223344",
    whatsapp: "77002223344",
    instagram: "arman.show",
    image: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&q=80&w=1200",
    features: ["KZ/RU", "Live band partner", "Script", "Games"],
    availableDates: ["2026-06-27", "2026-08-08", "2026-10-10"],
  },
];

export const DEFAULT_EVENT = {
  id: "event-main",
  type: "Үйлену той",
  title: "Айдана мен Әлидің тойы",
  date: "2026-09-12",
  city: "Алматы",
  guestCount: 180,
  budget: 6500000,
  progress: 42,
};

export const DEFAULT_GUESTS = [
  { id: "g1", name: "Гүлнар апай", phone: "+77010000001", relation: "туыс", status: "coming", plusOne: true, children: 0, tableId: "t1" },
  { id: "g2", name: "Ерлан", phone: "+77010000002", relation: "дос", status: "unknown", plusOne: false, children: 0, tableId: "" },
  { id: "g3", name: "Айгерім", phone: "+77010000003", relation: "қыз жақ", status: "invited", plusOne: true, children: 1, tableId: "t2" },
];

export const DEFAULT_BUDGET = [
  { id: "b1", category: "зал", title: "Банкет залы", planned: 3200000, actual: 0, paid: false },
  { id: "b2", category: "фото/видео", title: "Фото және видео", planned: 650000, actual: 250000, paid: true },
  { id: "b3", category: "декор", title: "Сахна декоры", planned: 420000, actual: 0, paid: false },
];

export const DEFAULT_CHECKLIST = [
  { id: "c1", group: "6 ай қалғанда", title: "Күнді бекіту және бюджет шегін анықтау", done: true, dueDate: "2026-03-01", reminder: false },
  { id: "c2", group: "3 ай қалғанда", title: "Зал мен тамаданы брондау", done: false, dueDate: "2026-06-01", reminder: true },
  { id: "c3", group: "1 ай қалғанда", title: "Қонақтар тізімін нақтылау", done: false, dueDate: "2026-08-12", reminder: true },
  { id: "c4", group: "1 апта қалғанда", title: "Таймингті барлық жауаптылармен бекіту", done: false, dueDate: "2026-09-05", reminder: true },
  { id: "c5", group: "той күні", title: "Декор, фото, музыка check-in", done: false, dueDate: "2026-09-12", reminder: false },
];

export const DEFAULT_TABLES = [
  { id: "t1", name: "Төр жақ", capacity: 10, note: "" },
  { id: "t2", name: "Достар", capacity: 12, note: "Құда жақпен араластырмау" },
];

export const DEFAULT_TIMELINE = [
  { id: "tl1", time: "17:00", title: "Қонақтарды қарсы алу", responsible: "Координатор", note: "Welcome zone дайын болсын" },
  { id: "tl2", time: "18:00", title: "Жас жұбайлар кіреді", responsible: "Тамада", note: "" },
  { id: "tl3", time: "18:20", title: "Беташар", responsible: "Тамада", note: "Музыка алдын ала тексерілсін" },
  { id: "tl4", time: "19:00", title: "Бірінші би", responsible: "DJ", note: "" },
  { id: "tl5", time: "22:00", title: "Торт", responsible: "Координатор", note: "Шамдар дайын" },
  { id: "tl6", time: "23:30", title: "Финал", responsible: "Тамада", note: "" },
];

export const BOOKING_STATUSES = {
  pending: "Ожидает подтверждения",
  confirmed: "Подтверждено",
  depositPaid: "Оплачен депозит",
  cancelled: "Отменено",
  completed: "Завершено",
  declined: "Отклонено",
};
